### PR TITLE
Isaac

### PR DESCRIPTION
**Pull request by dingbat-weasel**
server.js and initial files

### CODE REVIEW

**Review by Twenty-FourSeven — APPROVED** [review]
Excellent!

**Review by Twenty-FourSeven — APPROVED** [review]
Excellent!

**Comment by Twenty-FourSeven** [comment]
Excellent!

**Review by Twenty-FourSeven — APPROVED** [review]
Excellent!

**Review by jgerona — APPROVED** [review]
Looks good

**Pull request merged**
